# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/covogreen

    steps:
      - checkout

      - run:
          name: Update covogreen-back
          command: cd ~/covogreen/covogreen-back && npm install

      - run:
          name: Update covogreen-front
          command: cd ~/covogreen/covogreen-front && npm install

      # run tests!
      - run: cd ~/covogreen/covogreen-back && npm test

      - run:
          name: Test covogreen-back
          command: cd ~/covogreen/covogreen-back && npm test

      - run:
          name: Test covogreen-front
          command: cd ~/covogreen/covogreen-front && npm test