# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/covogreen

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/covogreen/covogreen-back/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # On installe les dépendances covogreen-back.
      - run:
          name: Update covogreen-back
          command: cd ~/covogreen/covogreen-back && npm install



      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "~/covogreen/covogreen-front/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
            
      # On installe les dépendances covogreen-front.
      - run:
          name: Update covogreen-front
          command: cd ~/covogreen/covogreen-front && npm install

      # On restore le cache si on a déjà dll les dependances covogreen-back.
      - save_cache:
          paths:
            - ~/covogreen/covogreen-back/node_modules
          key: v1-dependencies-{{ checksum "~/covogreen/covogreen-back/package.json" }}

      # On restore le cache si on a déjà dll les dependances covogreen-front.
      - save_cache:
          paths:
            - ~/covogreen/covogreen-front/node_modules
          key: v2-dependencies-{{ checksum "~/covogreen/covogreen-front/package.json" }}

      # On lance le test du covogreen-back.
      - run:
          name: Test covogreen-back
          command: cd ~/covogreen/covogreen-back && npm test

      # On lance le test du covogreen-front.
      - run:
          name: Test covogreen-front
          command: cd ~/covogreen/covogreen-front && npm test